import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

import { Toast } from "@heroui/react";
import { NavbarComponent } from "./_components/navbar";

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable}`} lang="en">
			<body className="min-h-screen bg-background antialiased">
				<TRPCReactProvider>
					<Toast.Provider />
					<div className="relative flex min-h-screen flex-col">
						<NavbarComponent />
						<main className="flex-1">{children}</main>
					</div>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
